In [37]:
import pandas as pd
import numpy as np

In [38]:
def factorial(n):
    if n <= 0:
        return 0
    else:
        result = 1
        currentNumber = n 
        while currentNumber > 0:
            result *= currentNumber
            currentNumber -= 1
    
        return result
    

In [39]:
factorial(5)

120

In [40]:
def fibonacci(n):
    if n<= 0:
        return
    else:
        num1 = 0
        num2 = 1
        for i in range(n):
            print(num1)
            temp = num1 + num2 
            num1 = num2 
            num2 = temp 
            
    

In [41]:
fibonacci(10)

0
1
1
2
3
5
8
13
21
34


In [42]:
series = pd.Series([10,20,30,40,50])

In [43]:
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [44]:
series[4]

50

In [45]:
series = pd.Series([10,20,30,40,50,55],['one','two','three','four','five','five'])

In [46]:
series

one      10
two      20
three    30
four     40
five     50
five     55
dtype: int64

In [47]:
series['five']

five    50
five    55
dtype: int64

In [48]:
date1 = pd.date_range('2022-10-1',  periods=6, freq='M')

In [49]:
date1

DatetimeIndex(['2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31',
               '2023-02-28', '2023-03-31'],
              dtype='datetime64[ns]', freq='M')

In [50]:
date1 = pd.date_range('2022-10-1',  periods=6, freq='Y')
date1

DatetimeIndex(['2022-12-31', '2023-12-31', '2024-12-31', '2025-12-31',
               '2026-12-31', '2027-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [51]:
date1 = pd.date_range('2022-10-1',  periods=6, freq='H')
date1

DatetimeIndex(['2022-10-01 00:00:00', '2022-10-01 01:00:00',
               '2022-10-01 02:00:00', '2022-10-01 03:00:00',
               '2022-10-01 04:00:00', '2022-10-01 05:00:00'],
              dtype='datetime64[ns]', freq='H')

In [54]:
#create dataframe with random numbers 
print(np.random.randn(2,3,4))

[[[ 0.43828246  1.589385    1.1699426  -0.6887482 ]
  [ 0.23663784 -1.03951468 -0.78970707 -1.18379115]
  [ 0.90104392 -0.96823144 -0.31315675 -0.7761377 ]]

 [[ 0.48488223  1.71748236 -0.98598733  1.18944821]
  [ 0.65182424 -0.48289512  1.8919828   0.08189683]
  [-1.82281437  0.72453001 -0.54557968  0.09810412]]]


In [59]:
#create simple dataframe with custom columns
dfSample = pd.DataFrame(np.random.randn(10,5), columns=['Col1','Col2','Col3','Col4','Col5'] )

print(dfSample)

       Col1      Col2      Col3      Col4      Col5
0  0.227653  0.751160 -1.541318 -1.195704  1.634673
1 -1.273593  1.360588 -0.821985  0.383179  1.686957
2  0.856239  1.090406 -0.170922 -0.733646 -1.210170
3 -0.505205  0.938800 -0.860122  2.899860 -0.182517
4 -0.113538  1.342076  0.560061 -1.122967  0.871974
5 -0.102389 -0.636814 -0.703713 -2.177939  1.257227
6  1.839321  0.330788  0.148447  0.514484 -1.112939
7  0.411830  1.591459  0.774349 -1.524169  1.133578
8 -1.122727  0.092884  1.242876 -0.935926 -0.222265
9 -1.196725 -1.406237  1.176931 -0.512847  0.557122


In [64]:
dfSample.shape

(10, 5)

In [66]:
#simple dataframe with custom column and custom index
dfSample = pd.DataFrame(np.random.randn(10,5), 
                        columns=['Col1','Col2','Col3','Col4','Col5'] , 
                        index=[10,11,12,13,14,15,16,17,18,19] )

print(dfSample)

        Col1      Col2      Col3      Col4      Col5
10 -0.094916  1.481645 -0.488854  0.937846  3.131363
11 -0.517247 -0.478715  1.485095  0.984463 -0.459282
12 -0.994509  0.809764 -1.166207  0.040214 -0.650022
13  0.782217 -0.752979 -0.770198 -0.043415 -2.765141
14  0.146800 -0.756703 -0.039913  0.743667  0.809275
15  0.491583  0.038567 -1.168911 -0.724116  1.534079
16  0.307686 -0.829831 -0.999759  1.463820 -1.232513
17  1.711874  1.049027  1.430938  0.374652  0.606585
18  0.841756  0.936706  1.041775  0.902274 -0.634650
19 -1.449658  0.581805 -0.109535 -0.688391 -0.461267


In [67]:
#access dataframe items using column names
dfSample['Col1']

10   -0.094916
11   -0.517247
12   -0.994509
13    0.782217
14    0.146800
15    0.491583
16    0.307686
17    1.711874
18    0.841756
19   -1.449658
Name: Col1, dtype: float64

In [79]:
#access dataframe items - multimple columns  
dfSample[['Col1','Col3']]

Col1      Col3
10 -0.094916 -0.488854
11 -0.517247  1.485095
12 -0.994509 -1.166207
13  0.782217 -0.770198
14  0.146800 -0.039913
15  0.491583 -1.168911
16  0.307686 -0.999759
17  1.711874  1.430938
18  0.841756  1.041775
19 -1.449658 -0.109535

In [81]:
#simple dataframe with custom column and custom index - made string index
dfSample = pd.DataFrame(np.random.randn(10,5), 
                        columns=['Col1','Col2','Col3','Col4','Col5'] , 
                        index=['10','11','12','13','14','15','16','17','18','19'] )

print(dfSample)

        Col1      Col2      Col3      Col4      Col5
10 -0.371834 -0.933833 -0.249429 -0.381751 -0.461077
11 -0.885528 -1.475598  1.059047  0.033065 -0.206319
12  1.186723  0.695060 -0.477619  2.550594 -0.688871
13  0.562038  1.075616  1.207477 -1.175954  1.435113
14 -0.776997  0.036757  2.039938  0.454630  0.075555
15 -0.518288 -0.530460 -1.073619 -1.644625  0.304601
16  0.492653  0.944925 -0.461744  0.091581 -0.539847
17  0.455497 -0.087119  1.166646  0.451089 -0.502932
18  1.923519  0.226696  1.982002  0.158319  0.606035
19  1.641007 -0.985923 -1.529901  0.584514 -0.256624


In [89]:
#access datafrme  by row numbers 
dfSample[0:3]

Col1      Col2      Col3      Col4      Col5
10 -0.371834 -0.933833 -0.249429 -0.381751 -0.461077
11 -0.885528 -1.475598  1.059047  0.033065 -0.206319
12  1.186723  0.695060 -0.477619  2.550594 -0.688871

In [90]:
#access datafrme  by indexes  ( there is no -1 for index )
dfSample['11':'15']

Col1      Col2      Col3      Col4      Col5
11 -0.885528 -1.475598  1.059047  0.033065 -0.206319
12  1.186723  0.695060 -0.477619  2.550594 -0.688871
13  0.562038  1.075616  1.207477 -1.175954  1.435113
14 -0.776997  0.036757  2.039938  0.454630  0.075555
15 -0.518288 -0.530460 -1.073619 -1.644625  0.304601

In [91]:
#apply transpose on dataframe 
dfSample.T

10        11        12        13        14        15        16  \
Col1 -0.371834 -0.885528  1.186723  0.562038 -0.776997 -0.518288  0.492653   
Col2 -0.933833 -1.475598  0.695060  1.075616  0.036757 -0.530460  0.944925   
Col3 -0.249429  1.059047 -0.477619  1.207477  2.039938 -1.073619 -0.461744   
Col4 -0.381751  0.033065  2.550594 -1.175954  0.454630 -1.644625  0.091581   
Col5 -0.461077 -0.206319 -0.688871  1.435113  0.075555  0.304601 -0.539847   

            17        18        19  
Col1  0.455497  1.923519  1.641007  
Col2 -0.087119  0.226696 -0.985923  
Col3  1.166646  1.982002 -1.529901  
Col4  0.451089  0.158319  0.584514  
Col5 -0.502932  0.606035 -0.256624

In [93]:
#numpy arrays 
npArray = np.array([1,2,3,4,5])
npArray

array([1, 2, 3, 4, 5])

In [94]:
npArray = np.array([[1,2],[3,4],[5,6]])
npArray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
arr = np.array([[[1,2,3,4],
[4,5,6,7],
[9,10,11,12]],
[[13,14,15,16],
[17,18,19,20],
[21,22,23,24]]])

In [96]:
arr

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [98]:
arr[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [99]:
arr[1,2]

array([21, 22, 23, 24])

In [100]:
arr[1,2,2]

23

In [102]:
#apply slicing 
#print from first outer group first and second row elements 
arr[0,0:3]


array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])